# Generated by Django 4.2 on 2023-04-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0002_customuser_bio_customuser_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(default="avatar.jpg", null=True, upload_to=""),
        ),
    ]
