# Generated by Django 4.2 on 2023-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0003_customuser_avatar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
