# Generated by Django 4.2 on 2023-04-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0004_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_email_verified",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
