# Generated by Django 4.2 on 2023-04-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0005_remove_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
