# Generated by Django 4.2 on 2023-04-21 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_competition_competitionteam_rating_sport_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.students'),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.students'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
