# Generated by Django 4.2 on 2023-04-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_students_alter_rating_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'students'},
        ),
    ]
