# Generated by Django 4.2 on 2023-04-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': ('student',)},
        ),
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
