# Generated by Django 4.2 on 2023-04-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_alter_students_options_alter_students_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='sport',
            new_name='sport_id',
        ),
        migrations.RenameField(
            model_name='competitionteam',
            old_name='competition',
            new_name='competition_id',
        ),
        migrations.RenameField(
            model_name='competitionteam',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='studentteam',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='studentteam',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sport',
            new_name='sport_id',
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition_id', 'team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('student_id', 'team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='studentteam',
            unique_together={('student_id', 'team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('team_name', 'sport_id')},
        ),
        migrations.AlterModelTable(
            name='competition',
            table='competitions',
        ),
        migrations.AlterModelTable(
            name='competitionteam',
            table='competition_teams',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
        migrations.AlterModelTable(
            name='sport',
            table='sports',
        ),
        migrations.AlterModelTable(
            name='studentteam',
            table='student_team',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
